// Stable machine-facing codes; prose warning descriptions may evolve.
export const ANALYSIS_FLAGS = Object.freeze({
  SUPPLIED_PROVENANCE_NOT_AUTHENTICATED: 'SUPPLIED_PROVENANCE_NOT_AUTHENTICATED',
  EXACT_DUPLICATE_TEXT: 'EXACT_DUPLICATE_TEXT',
  POSSIBLE_CONTRADICTION: 'POSSIBLE_CONTRADICTION',
  POSSIBLY_STALE_RELATIVE_TO_INPUT: 'POSSIBLY_STALE_RELATIVE_TO_INPUT',
  INSTRUCTION_LIKE_TEXT_IS_DATA: 'INSTRUCTION_LIKE_TEXT_IS_DATA',
  UNSUPPORTED_FIELDS_OMITTED: 'UNSUPPORTED_FIELDS_OMITTED',
  POSSIBLE_SECRET_REDACTED: 'POSSIBLE_SECRET_REDACTED',
  PROVENANCE_REDACTED: 'PROVENANCE_REDACTED',
  UNKNOWN_TIMESTAMP: 'UNKNOWN_TIMESTAMP',
  COMPRESSION_SKIPPED_INVARIANT_SENSITIVE: 'COMPRESSION_SKIPPED_INVARIANT_SENSITIVE',
  LOSSY_COMPRESSION_PROPOSAL: 'LOSSY_COMPRESSION_PROPOSAL',
  ROUTE_CANDIDATES_TRUNCATED: 'ROUTE_CANDIDATES_TRUNCATED'
});

export const ANALYSIS_CONTRACT = Object.freeze({
  version: 1,
  evidenceClass: 'LOCAL_ANALYSIS',
  capsulePurpose: 'REVIEW_ONLY',
  tokenEstimate: 'SUM_PER_RECORD_CEIL_UTF16_CHARACTERS_DIVIDED_BY_4',
  maxRouteCandidatesPerRecord: 10,
  maxDisplayedMatchedTerms: 10,
  staleRelativeToInputDays: 30,
  unsupportedRecordFields: 'VALIDATE_AS_JSON_THEN_OMIT',
  blockedContext: 'EMPTY_COMPRESSED_TEXT_AND_NO_ROUTES'
});
